id: I0DC2F740
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-17T23:09:40+00:00'
last_modified: '2022-06-10T05:13:58.646245+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3PD430
  title: བོད་ཀྱི་བཀྲ་ཤིས་པའི་རྒྱུན་རིས་གསར་འགྲེལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    BBA6:
      image_group_id: I2PD17816
      title: Volume 1 of bod kyi bkra shis pa'i rgyun ris gsar 'grel/
      total_pages: 176
      order: 1
      base_file: BBA6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
